spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to BiharBank accounts related QA APIs "
  contactDetails:
    name: "Sushant Kumar - QA Lead"
    email: "sushant@biharbank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345