services:
  accounts:
    image: "digitalsushant/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -biharbank

  loans:
    image: "digitalsushant/loans:s2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -biharbank

  cards:
    image: "digitalsushant/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -biharbank

networks:
 biharbank:
  driver: "bridge"